In [1]:
# Day 3: NumPy Indexing & Slicing

import numpy as np

In [2]:
# Program 1 : Create a 1D Array

arr1 = np.array([10 , 20 , 30 , 40 , 50])

print(arr1)

[10 20 30 40 50]


In [8]:
# Program 2 : Indexing

print(arr1[0])
print(arr1[2])
print(arr1[4])

10
30
50


In [12]:
# Program 3 : Negative Indexing

print(arr1[-1])
print(arr1[-4])
print(arr1[-5])

50
20
10


In [14]:
# Program 4 : Basic Slicing

print(arr1[:4]) 
print(arr1[:2])

[10 20 30 40]
[10 20]


In [15]:
# Program 5 : Slice from Beginning

print(arr1[:3])

[10 20 30]


In [19]:
# Program 6 : Slice to end

print(arr1[2:])
print(arr1[1:])

[30 40 50]
[20 30 40 50]


In [23]:
# Program 7 : Step Slicing

print(arr1[::1])
print(arr1[::2])
print(arr1[::3])

[10 20 30 40 50]
[10 30 50]
[10 40]


In [27]:
# Program 8 : Reverse Array

print(arr1[::-1])

[50 40 30 20 10]


In [31]:
# Program 9 : 2D array Indexing

arr = np.array([
    [1 , 2 , 3] ,
    [4 , 5 , 6] ,
    [7 , 8 , 9]
])

print(arr[0 , 2])
print(arr[2 , 2])
print(arr[2 , 1])

3
9
8


In [32]:
# Program 10 : 2D array Slicing

print(arr[:,1])
print(arr[1: , :2])

[2 5 8]
[[4 5]
 [7 8]]


In [33]:
# Mini Project: Student Marks Analysis

marks = np.array([
    [85,90,78],
    [88,76,92],
    [95,89,84]
])

print("Marks:")
print(marks)

print("\nFirst Student:")
print(marks[0])

print("\nSecond Subject:")
print(marks[:,1])

print("\nLast Student:")
print(marks[-1])

print("\nFirst Two Students:")
print(marks[:2])

print("\nReverse Order:")
print(marks[::-1])

Marks:
[[85 90 78]
 [88 76 92]
 [95 89 84]]

First Student:
[85 90 78]

Second Subject:
[90 76 89]

Last Student:
[95 89 84]

First Two Students:
[[85 90 78]
 [88 76 92]]

Reverse Order:
[[95 89 84]
 [88 76 92]
 [85 90 78]]
