In [1]:
# Day 7: NumPy Splitting Arrays

import numpy as np

In [5]:
# Program 1 : Split a 1D Array

arr = np.array([10 , 20 , 30 , 40 , 50 ])

result = np.array_split(arr , 3)

print(result)

[array([10, 20]), array([30, 40]), array([50])]


In [8]:
# Program 2 : Split intp equal parts

arr = np.array([1 , 2 , 3 , 4 , 5 , 6])

result = np.split(arr , 3)

print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [18]:
# Program 3 : Split at Specific Index

arr = np.array([1 , 2 , 3 , 4 , 5 , 6])

result = np.split(arr , [1 , 3])

print(result)


[array([1]), array([2, 3]), array([4, 5, 6])]


In [23]:
# Program 4 : Split a 2D Array (Rows)

arr = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]])

result = np.array_split(arr , 2 , axis = 0)

for i in result :
    print(i)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [25]:
# Program 5 : Split a 2D Array (Colums)

arr = np.array([[1,2,3,4],
                [5,6,7,8]
                ])

result = np.array_split(arr , 2 , axis = 1)

for i in result :
    print(i)

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [ ]:
# Program 6 : hsplit() (column-wise)

arr = np.array([[1,2,3,4],
                [5,6,7,8]
                ])

result = np.hsplit(arr,2)

for i in result :
    print(i)

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [27]:
# Program 7 : vsplit() (row-wise)

arr = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]])

result = np.vsplit(arr , 2)

for i in result :
    print(i)



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [28]:
# Program 8 : Split Unequal Parts

arr = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 ])

result = np.array_split(arr , 3)

print(result)

[array([10, 20, 30]), array([40, 50]), array([60, 70])]


In [29]:
# Program 9 : Compare split() and array_split()

arr = np.array([1,2,3,4,5,6,7])

print("array_split():")
print(np.array_split(arr, 3))

print("\nsplit()")

try:
    print(np.split(arr, 3))
except ValueError as e:
    print(e)

array_split():
[array([1, 2, 3]), array([4, 5]), array([6, 7])]

split()
array split does not result in an equal division


In [30]:
# Mini Project: Student Marks Split

marks = np.array([85, 90, 78, 88, 92, 75, 81, 95])

parts = np.array_split(marks, 4)

for i, part in enumerate(parts):
    print(f"Group {i+1}:")
    print(part)

Group 1:
[85 90]
Group 2:
[78 88]
Group 3:
[92 75]
Group 4:
[81 95]
