In [1]:
# Day 9 : NumPy Sorting and Searching

import numpy as np

In [2]:
# Program 1 : Sort a 1D Array

arr = np.array([5,7,10,1,2,9])

sorted = np.sort(arr)

print(sorted)

[ 1  2  5  7  9 10]


In [4]:
# Program 2 : Sort a String Array

arr = np.array(["Banana" , "Apple" , "Mango" , "Orange"])

sorted = np.sort(arr)

print(sorted)

['Apple' 'Banana' 'Mango' 'Orange']


In [6]:
# Program 3 : Sort a 2D Array

arr = np.array([
    [1 , 8 , 7],
    [3 , 10 , 9]
])

sorted = np.sort(arr)

print(sorted)

[[ 1  7  8]
 [ 3  9 10]]


In [7]:
# Program 4 : argsort()

arr = np.array([50 , 20 , 10 , 40 , 30])

print("Original Array : ",arr)

print("Sorted Indexes : ")
print(np.argsort(arr))

Original Array :  [50 20 10 40 30]
Sorted Indexes : 
[2 1 4 3 0]


In [8]:
# Program 5 : where()

arr = np.array([50 , 20 , 10 , 20 , 30 , 20])

print(np.where(arr == 20))

(array([1, 3, 5]),)


In [10]:
# Program 6 : searchsorted()

arr = np.array([10,20,30,40,50])

print(np.searchsorted(arr , 25))

2


In [ ]:
# Program 7: searchsorted() Multiple Values

arr = np.array([10, 20, 30, 40, 50])

print(np.searchsorted(arr, [15, 25, 45]))

[1 2 4]


In [12]:
# Program 8 : Extract Even Numbers

arr = np.array([2 , 5 , 7 , 4 , 11 , 12 , 14 , 16 , 15])

print(arr[arr % 2 ==0])

[ 2  4 12 14 16]


In [13]:
# Program 9 : Extract Odd Numbers

arr = np.array([2 , 5 , 7 , 4 , 11 , 12 , 14 , 16 , 15])

print(arr[arr % 2 != 0])


[ 5  7 11 15]


In [ ]:
# Program 10 : Find Maximum and Minimum Index

arr = np.array([2 , 5 , 7 , 4 , 11 , 12 , 14 , 16 , 15])

print("Maximum Index : ",np.argmax(arr))

print("Minimum Index : ",np.argmin(arr))

Maximum Index :  7
Minimum Index :  0


In [15]:
## Mini Project: Student Marks Analysis

marks = np.array([75, 92, 68, 88, 95, 81])

print("Original Marks:")
print(marks)

print("\nSorted Marks:")
print(np.sort(marks))

print("\nHighest Marks Index:")
print(np.argmax(marks))

print("\nLowest Marks Index:")
print(np.argmin(marks))

print("\nMarks Greater Than 80:")
print(marks[marks > 80])

Original Marks:
[75 92 68 88 95 81]

Sorted Marks:
[68 75 81 88 92 95]

Highest Marks Index:
4

Lowest Marks Index:
2

Marks Greater Than 80:
[92 88 95 81]
