In [4]:
import numpy as np


In [5]:
# Program 1: Create a 1D Array

arr1 = np.array([ 1 , 2 , 3 , 4 , 5 ])
print(arr1)

[1 2 3 4 5]


In [7]:
# Program 2: Create a 2D Array

arr2 = np.array([[1 , 2 , 3 ] ,
                 [ 4 , 5 , 6 ]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
# Program 3: Find Shape

print(arr2.shape)

(2, 3)


In [10]:
# Program 4: Find Dimensions

print(arr2.ndim)

2


In [11]:
# Program 5: Find Size

print(arr2.size)

6


In [13]:
# Program 6: Find Data Type

print(arr1.dtype)
print(arr2.dtype)

int64
int64


In [14]:
# Program 7: Convert List to NumPy Array

numbers = [ 1 , 2 , 3 , 4 , 5 , 6 ]

arr = np.array(numbers)

print(arr)



[1 2 3 4 5 6]
