In [2]:
# Day 5: NumPy Array Manipulation

import numpy as np

In [3]:
# Program 1: Reshape an Array

arr = np.arange(1, 13)

print("Original Array:")
print(arr)

print("\nReshaped Array:")
print(arr.reshape(3, 4))

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
# Program 2 : Flatten a 2D Array

arr = np.array([
    [1,2,3] ,
    [4,5,6]
])

print(arr.flatten())


[1 2 3 4 5 6]


In [7]:
# Program 3 : Ravel on Array

arr = np.array([
    [1,2,3] ,
    [4,5,6]
])

print(arr.ravel())

[1 2 3 4 5 6]


In [9]:
# Program: Difference Between ravel() and flatten()

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Create ravel and flatten arrays
ravel_arr = arr.ravel()
flatten_arr = arr.flatten()

# Modify both arrays
ravel_arr[0] = 100
flatten_arr[1] = 200

print("Original Array:")
print(arr)

print("\nRavel Array:")
print(ravel_arr)

print("\nFlatten Array:")
print(flatten_arr)

# ravel() : returns a view, so changing ravel_arr also changes the original array.
# flatten() : returns a copy, so changing flatten_arr does not affect the original array

Original Array:
[[100   2   3]
 [  4   5   6]]

Ravel Array:
[100   2   3   4   5   6]

Flatten Array:
[  1 200   3   4   5   6]


In [10]:
# Program 4: Transpose a Matrix

arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
# Program 5 : Resize an Array

arr = np.array([1,2,3,4,5,6])

print(np.resize(arr,(3,4)))

[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]


In [13]:
# Program 6 : Change Shape

arr = np.arange(1,17)

print(arr.shape)

new_arr = arr.reshape(4,4)

print(new_arr)

(16,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [14]:
# Program 7 : Flatten Using reshape()

arr = np.array([
    [10 , 20] ,
    [30,40]
])

print(arr.reshape(-1))

[10 20 30 40]


In [15]:
# Program 8 : Convert 1D to 2D

arr = np.arange(1,10)

print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# Program 9 : Convert 2D to 1D

arr = np.array([
    [1 , 2 , 3] ,
    [4 , 5 , 6]  
])

print(arr.flatten())

[1 2 3 4 5 6]


In [17]:
# Program 10 : Copy vs View

arr = np.array([10 , 20 , 30 , 40 ])

copy_arr =  arr.copy()
view_arr = arr.view()

arr[0] = 100

print("Original : ",arr)

print("Copy : ",copy_arr)

print("View : ",view_arr)

Original :  [100  20  30  40]
Copy :  [10 20 30 40]
View :  [100  20  30  40]


In [ ]:
# Mini Project: Student Marks Table

marks = np.array([
    [80,85,90],
    [75,88,92],
    [95,91,89],
    [78,82,84]
])

print("Marks Table:")
print(marks)

print("\nFlattened:")
print(marks.flatten())

print("\nTranspose:")
print(marks.T)

print("\nReshaped (2 x 6):")
print(marks.reshape(2,6))