In [1]:
# Day 4: NumPy Array Operations

import numpy as np

In [ ]:
# Program 1 : Addition of Two Arrays

arr1 = np.array([10 , 20 , 30])
arr2 = np.array([5 , 10 , 15])

print(arr1 + arr2)

[15 30 45]


In [4]:
# Program 2 : Substraction of Two Arrays

arr1 = np.array([10 , 20 , 30])
arr2 = np.array([5 , 10 , 15])

print(arr1 - arr2)

[ 5 10 15]


In [5]:
# Program 3 : Multiplication of Two Arrays 

arr1 = np.array([2, 4, 6])
arr2 = np.array([3, 5, 7])

print(arr1 * arr2)

[ 6 20 42]


In [6]:
# Program 4: Division of Two Arrays

arr1 = np.array([20, 40, 60])
arr2 = np.array([2, 4, 5])

print(arr1 / arr2)

[10. 10. 12.]


In [ ]:
# Program 6: Square Root
 
arr = np.array([2 , 3 , 4])

print(arr ** 2)

[ 4  9 16]


In [8]:
arr = np.array([2 , 3 , 4])

print(np.sum(arr))

9


In [11]:
# Program 8: Mean, Maximum , Minimum and Standard Deviation

arr = np.array([10,20,30,40,50])

print("\nMean : ",np.mean(arr))

print("\nMaximum : ",np.max(arr))

print("\nMinimum : ",np.min(arr))

print("\nStandard Deviation : ",np.std(arr))


Mean :  30.0

Maximum :  50

Minimum :  10

Standard Deviation :  14.142135623730951


In [16]:
# Program 9 : Reshape an Array

arr = np.arange(1 , 10)

print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# Mini Project: Student Marks Analysis

marks = np.array([75, 82, 91, 68, 88])

print("Marks:", marks)

print("Total Marks:", np.sum(marks))
print("Average Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Standard Deviation:", np.std(marks))

print("\nReshaped Array:")
print(marks.reshape(5,1))

Marks: [75 82 91 68 88]
Total Marks: 404
Average Marks: 80.8
Highest Marks: 91
Lowest Marks: 68
Standard Deviation: 8.423775875461075

Reshaped Array:
[[75]
 [82]
 [91]
 [68]
 [88]]
