In [1]:
# Day 8: NumPy Boolean Indexing & Filtering

import numpy as np

In [2]:
# Program 1 : Boolean Condition 

arr = np.array([10 , 25 , 30 , 45 , 50 , 65 ])

condition = arr > 30

print(condition)

[False False False  True  True  True]


In [3]:
# Program 2 : Filter values greater than 30

arr = np.array([10 , 25 , 30 , 45 , 50 , 65 ])

condition = arr[arr > 30]

print(condition)

[45 50 65]


In [4]:
# Program 3 : Filter even numbers

arr = np.array([4 , 5 , 7 , 12 , 15 , 14 , 16 , 21])

condition = arr[arr % 2 == 0]

print(condition)

[ 4 12 14 16]


In [ ]:
# Program 4 : Filter odd numbers

arr = np.array([4 , 5 , 7 , 12 , 15 , 14 , 16 , 21])

condition = arr[arr % 2 != 0]

print(condition)

[ 5  7 15 21]


In [12]:
# Program 5 : Multiple condition using (&) and (|)


arr = np.array([4 , 5 , 7 , 12 , 15 , 14 , 16 , 21])

result = arr[(arr > 10) &  (arr < 16)]

print(result)

print("\n")

result2 = arr[(arr < 10) | (arr > 15)]
print(result2)

[12 15 14]


[ 4  5  7 16 21]


In [13]:
# Program 6 : Replace Values Using Boolean Indexing


arr = np.array([4 , 5 , 7 , 12 , 15 , 14 , 16 , 21])

arr[arr > 15] = 100

print(arr)

[  4   5   7  12  15  14 100 100]


In [ ]:
# Program 7 : np.where()

arr = np.array([10 , 25 , 30 , 45 , 50])

result = np.where(arr > 30 , "High" , "Low")

print(result)

['Low' 'Low' 'Low' 'High' 'High']


In [ ]:
# Program 8 : Filter a 2D Array

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

result = arr[arr > 50]

print(result)

[60 70 80 90]


In [ ]:
# Mini Project: Student Marks Analysis

marks = np.array([35, 72, 48, 91, 67, 29, 85])

print("All Marks:")
print(marks)

print("\nPassed Students (>= 40):")
print(marks[marks >= 40])

print("\nFailed Students (< 40):")
print(marks[marks < 40])

print("\nExcellent Students (>= 80):")
print(marks[marks >= 80])

print("\nResult Status:")
print(np.where(marks >= 40, "Pass", "Fail"))

All Marks:
[35 72 48 91 67 29 85]

Passed Students (>= 40):
[72 48 91 67 85]

Failed Students (< 40):
[35 29]

Excellent Students (>= 80):
[91 85]

Result Status:
['Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass']
