In [1]:
# Day 6: NumPy Joining Arrays

import numpy as np

In [3]:
# Program 1 : Concatenate 1D Arrays

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.concatenate((arr1,arr2))

print(result)


[1 2 3 4 5 6]


In [6]:
# Program 2 : Concatenate 2D Arrays

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])



# For rows

print(np.concatenate((arr1,arr2) , axis = 0))

print("\n")

# For columns

print(np.concatenate((arr1 , arr2) , axis = 1))



[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


In [7]:
# Program 3 : Horizontal Stack (hstack)

arr1 = np.array([10 , 20 , 30])
arr2 = np.array([40 , 50 , 60])

result = np.hstack((arr1,arr2))

print(result)

[10 20 30 40 50 60]


In [ ]:
# Program 4 : Vertical Stack (vstack)

arr1 = np.array([10 , 20 , 30])
arr2 = np.array([40 , 50 , 60])

result = np.vstack((arr1,arr2))

print(result)

[[10 20 30]
 [40 50 60]]


In [9]:
# Program 5 : Depth Stack (dstack)

arr1 = np.array([10 , 20 , 30])
arr2 = np.array([40 , 50 , 60])

result = np.dstack((arr1,arr2))

print(result)

[[[10 40]
  [20 50]
  [30 60]]]


In [10]:
# Program 6 : Column Stack

arr1 = np.array([10 , 20 , 30])
arr2 = np.array([40 , 50 , 60])

result = np.column_stack((arr1,arr2))

print(result)

[[10 40]
 [20 50]
 [30 60]]


In [14]:
# Program 7 : Stack() 

arr1 = np.array([10 , 20 , 30])
arr2 = np.array([40 , 50 , 60])

print("Axis = 0")
print(np.stack((arr1,arr2) , axis=0))

print("\nAxis = 1")
print(np.stack((arr1,arr2), axis=1))

Axis = 0
[[10 20 30]
 [40 50 60]]

Axis = 1
[[10 40]
 [20 50]
 [30 60]]


In [15]:
## Mini Project: Student Data Joining

roll_no = np.array([101, 102, 103])
marks = np.array([85, 90, 78])

print("Column Stack:")
print(np.column_stack((roll_no, marks)))

print("\nHorizontal Stack:")
print(np.hstack((roll_no, marks)))

print("\nVertical Stack:")
print(np.vstack((roll_no, marks)))

Column Stack:
[[101  85]
 [102  90]
 [103  78]]

Horizontal Stack:
[101 102 103  85  90  78]

Vertical Stack:
[[101 102 103]
 [ 85  90  78]]
