In [ ]:
# Day 2 - NumPy Array Creation Functions

import numpy as np

In [5]:
# Program 1: Create a 1D array of zeros

arr1 = np.zeros(6)

print(arr1)

[0. 0. 0. 0. 0. 0.]


In [7]:
# Program 2: Create a 2D array of zeros

arr2 = np.zeros((3,3))

print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Program 3: Create a 1D array of ones

arr3 = np.ones(6)

print(arr3)

[1. 1. 1. 1. 1. 1.]


In [9]:
# Program 4: Create a 2D array of ones

arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Program 5: Create an array using arange()

arr = np.arange(6)

print(arr)

[0 1 2 3 4 5]


In [13]:
# Program 6: Create an array using arange() with step

arr = np.arange(1,20,2)

print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [16]:
# Program 7: Create an array using linspace()

arr = np.linspace(1,10,5)

print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [18]:
# Program 8: Create an identity matrix

arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Program 9: Generate random decimal numbers

# Random decimal numbers
arr = np.random.rand(5)
print(arr)

# Random integers between 1 and 10
arr1 = np.random.randint(1 , 10 , 5)
print(arr1)

[0.12370211 0.25321304 0.89074872 0.99565668 0.0148398 ]
[3 7 9 5 8]


In [25]:
# Mini Project: Student Roll Numbers

roll_numbers = np.arange(101,111)

print("Student Roll Numbers:")
print(roll_numbers)

identity = np.eye(5)
print("\nIdentity Matrix:")
print(identity)

random_marks = np.random.randint(50,101,10)
print("\nRandom Marks:")
print(random_marks)

Student Roll Numbers:
[101 102 103 104 105 106 107 108 109 110]

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Random Marks:
[72 79 74 67 82 54 95 71 90 75]
