In [1]:
# Day 10 : NumPy Broadcasting & Vectorization

import numpy as np

In [2]:
# Program 1 : Broadcasting with Scalar

arr = np.array([10 , 20 , 30 , 40 ])

print(arr + 5)

[15 25 35 45]


In [3]:
# Program 2 : Broadcasting two arrays

arr1 = np.array([1 , 2 , 3])
arr2 = np.array([10 , 20 , 30])

print(arr1 + arr2)

[11 22 33]


In [4]:
# Program 3 : Broadcasting 2D and 1D Arrays

arr1 = np.array([
    [1 , 2 , 3],
    [4 , 5 , 6]
])

arr2 =  np.array([7,8,9])

print(arr1 + arr2)

[[ 8 10 12]
 [11 13 15]]


In [5]:
# Program 4 : Broadcasting Multiplication

arr1 = np.array([
    [1 , 2 , 3],
    [4 , 5 , 6]
])

print(arr1 * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [6]:
# Program 5 : Vectorized Addition

arr = np.array([1 , 2 , 3])

print(arr + 5)





[6 7 8]


In [ ]:
# Program 6 : Vectorized Square

arr = np.array([1 , 2 , 3])

print(arr ** 2)

[1 4 9]


In [10]:
# Program 7 : Vectorized Square Root

arr = np.array([4 , 9 , 16 , 25])

print(np.sqrt(arr))

[2. 3. 4. 5.]


In [12]:
# Program 8 : Vectorized Comparison

arr = np.array([10 , 25 , 30 , 45 , 50])

print(arr > 30)

[False False False  True  True]


In [14]:
# Program 9 : Boolean Indexing with Vectorization

arr = np.array([10 , 25 , 30 , 45 , 80])

print(arr[arr>30])

[45 80]


In [19]:
# Program 10 : Compare Loop vs Vectorization

arr = np.array([1 , 2 , 3 , 4 , 5])

result = []

for i in arr :
    result.append(int(i * 2))

print("Using Loop : \n")
print(result)

print("\nUsing Vectorization : \n")
print(arr * 2)

Using Loop : 

[2, 4, 6, 8, 10]

Using Vectorization : 

[ 2  4  6  8 10]


In [20]:
# Mini Project: Employee Salary Increment

salary = np.array([25000, 30000, 35000, 40000])

print("Current Salary:")
print(salary)

increment = salary * 0.10

print("\n10% Increment:")
print(increment)

print("\nUpdated Salary:")
print(salary + increment)


Current Salary:
[25000 30000 35000 40000]

10% Increment:
[2500. 3000. 3500. 4000.]

Updated Salary:
[27500. 33000. 38500. 44000.]
